//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace RallyPortal
{
    public partial class GalleryCategory
    {
        public GalleryCategory()
        {
            this.Galleries = new HashSet<Gallery>();
            this.SubCategories = new HashSet<GalleryCategory>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public int GalleryCategoryId { get; set; }
        public Nullable<int> GalleryCategoryId1 { get; set; }
    
        public virtual ICollection<Gallery> Galleries { get; set; }
        public virtual ICollection<GalleryCategory> SubCategories { get; set; }
        public virtual GalleryCategory Parent { get; set; }
    }
    
}
