//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace RallyPortal
{
    public partial class ModelContainer : DbContext
    {
        public ModelContainer()
            : base("name=ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Article> ArticleSet { get; set; }
        public DbSet<Comment> CommentSet { get; set; }
        public DbSet<Team> TeamSet { get; set; }
        public DbSet<Image> ImageSet { get; set; }
        public DbSet<Gallery> GallerySet { get; set; }
        public DbSet<GalleryCategory> GalleryCategorySet { get; set; }
    }
}
