//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace RallyPortal
{
    public partial class Team
    {
        public int Id { get; set; }
        public string TeamName { get; set; }
        public string DriverName { get; set; }
        public string CoDriverName { get; set; }
        public string TeamImageUrl { get; set; }
        public string DriverImageUrl { get; set; }
        public string CoDriverImageUrl { get; set; }
        public string TeamSummary { get; set; }
        public string DriverSummary { get; set; }
        public string CoDriverSummary { get; set; }
    }
    
}
